language: cpp
version: 0.1.0

platform:
    - target : ubuntu
      version: 14.04
      arch : i686

api: 0.6.0

install:
    - sudo apt-get install -y libopencv-dev

build:
    - mkdir build
    - cd build
    - cmake ..
    - make

package:
    - build/learn_object
    - build/run.sh
